from typing import Optional as OptionalType

import logging

from flask import current_app
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, ValidationError, EmailField, BooleanField, TextAreaField, SelectMultipleField, SelectField
from wtforms.validators import DataRequired, EqualTo, Optional
import pytz
from sqlalchemy.exc import NoResultFound, MultipleResultsFound

from .. import event
from .models import User
from .process import exc, totp, email


logger = logging.getLogger(__name__)


def list_timezones():
    yield ('', "Select a Timezone")
    common = set(pytz.common_timezones)
    rest = set(pytz.all_timezones) - common
    sf = lambda t: (not t.startswith('America/'), t != 'UTC', t)
    for t in sorted(common | rest, key=sf):
        yield (t, t)


class ValidateRequiredIf:
    def __init__(self, other_name: str, message: str="Must be present if {other_title} is present"):
        self.other_name = other_name
        self.message = message

    def __call__(self, form, field):
        other_field = getattr(form, self.other_name)
        if other_field.data and not field.data:
            raise ValidationError(self.message.replace('{other_title}', other_field.label.text))


class LoginForm(FlaskForm):
    username_or_email = StringField('Username or Email', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Log In')

    def validate_on_submit(self):
        if super().validate_on_submit():
            # Custom implementation to avoid leaking data via timing
            user = None
            valid_user = False
            try:
                user = User.query.filter(
                    User.username.like(self.username_or_email.data)
                    | User.email.like(self.username_or_email.data)
                ).one()
                valid_user = True
            except NoResultFound:
                user = User.query.first()
            except MultipleResultsFound:
                logger.error("Found more than one user matching %s", self.username_or_email.data)

            if user:
                if user.password == self.password.data:
                    if valid_user:
                        return user
            # Return None if we checked, to indicate invalid info
            return None
        return False



class PasswordResetInitForm(FlaskForm):
    username_or_email = StringField('Username or Email', validators=[DataRequired()])
    submit = SubmitField('Reset Password')


class PasswordResetForm(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired()], description="Enter a strong random password to protect your account")
    repassword = PasswordField('Retype Password', validators=[DataRequired(), EqualTo('password', message="Both passwords must match")], description="Enter the same password again")
    submit = SubmitField('Log In')


class TOTPValidationForm(FlaskForm):
    def __init__(self, user: User, setup: bool=False, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user
        self.setup = setup

    code = StringField('Code', validators=[DataRequired()], description="Enter a code generated by your authenticator app to confirm the setup")
    submit = SubmitField('Validate')

    def validate_code(self, field):
        if self.setup:
            try:
                totp.complete_totp_setup(self.user, field.data)
            except exc.UserProcessError as e:
                raise ValidationError(str(e))
        else:
            if not self.user.validate_totp(field.data):
                raise ValidationError('Invalid code')


def UserForm(user: OptionalType[User], action: str):
    original_email = user.email if user else None
    current_user = event.publish('user.current')
    admin_edit = bool(current_user and current_user.can('edit_user_admin', 'edit_other_user_admin', obj=user))

    class UserEditForm(FlaskForm):
        if admin_edit or action == 'signup':
            username = StringField('Username', validators=[DataRequired()], description="Choose a unique username for your account")
        email = EmailField('Email Address', validators=[DataRequired()], description="Enter a valid email address")
        update_password = PasswordField('Password', validators=[DataRequired() if action == 'signup' else Optional()], description="Enter a strong random password to protect your account")
        update_repassword = PasswordField('Retype Password', validators=[ValidateRequiredIf('update_password'), DataRequired() if action == 'signup' else Optional(), EqualTo('update_password', message="Both passwords must match")], description="Enter the same password again")
        if action == 'edit':
            old_password = PasswordField('Current Password', validators=[ValidateRequiredIf('update_password'), Optional()], description="Enter your current password to change your password")
        name = StringField('Name', validators=[Optional()], description="Your name, may be displayed on the site")
        bio = TextAreaField('Bio', validators=[Optional()], description="Tell us a little about yourself")
        timezone = SelectField('Timezone', validators=[DataRequired()], choices=list(list_timezones()))
        if admin_edit:
            is_approved = BooleanField('Is Approved?', description="Is this account approved?")
            is_disabled = StringField('Disabled - Reason', validators=[Optional()], description="If this account is to be disabled, enter a reason (this is not shown to the user)")
            roles = SelectMultipleField('Roles', validators=[Optional()], description="Roles assigned to this user")
            permissions = SelectMultipleField('Permissions', validators=[Optional()], description="Permissions assigned to this user")

        submit = SubmitField('Sign Up' if action == 'signup' else 'Save Changes')

        def _validate_unique(self, model_field, form_field):
            query = User.query.filter(model_field.like(form_field.data))
            if user and user.id:
                query = query.filter(User.id != user.id)
            return query.count() == 0

        def validate_username(self, field):
            if hasattr(self, 'username'):
                if not self._validate_unique(User.username, field):
                    raise ValidationError("Username must be unique")

        def validate_email(self, field):
            if not self._validate_unique(User.email, field):
                raise ValidationError("Email must be unique")

        def validate_old_password(self, field):
            if not current_user:
                raise ValidationError("No user is logged in!")
            if not current_user.password == field.data:
                raise ValidationError("Password is not valid")

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            p = current_app.plugins['user']
            if hasattr(self, 'roles'):
                self.roles.choices = [(k, v['name']) for k, v in p.roles.items()]
            if hasattr(self, 'permissions'):
                self.permissions.choices = [(k, v['name']) for k, v in p.permissions.items()]
            self.timezone.default = current_app.config['SITE_TIMEZONE']

        def populate_obj(self, obj):
            if action == 'signup':
                raise RuntimeError("Cannot use populate_obj for signup")
            super().populate_obj(obj)
            # update password first
            if self.update_password.data:
                obj.password = self.update_password.data
            # If email has changed, begin the email confirmation process
            if self.email.data != original_email:
                obj.email = original_email
                email.begin_email_confirmation(obj, self.email.data)

    return UserEditForm(obj=user)
