"""Password hashing implementations"""

from typing import Dict, Union, Optional, Any

import hmac
import base64
import json
import hashlib
import os


class Password:
    """Represents a hashed password and the settings used to hash it"""

    def __init__(self, driver_name: str, salt: bytes, hashed_password: bytes, params: Dict[str, Union[str, int]]):
        """Create a new Password instance with the given salt and password, and parameters"""

        self.driver_name = driver_name
        self.salt = salt
        self.hashed_password = hashed_password
        self.params = params

    @property
    def driver(self):
        return globals()[self.driver_name](**self.params)

    def __eq__(self, other: Any) -> bool:
        """\
        Constant time comparison of all properties including the hash
        Comparing the hash only is probably good enough, but meh
        """

        if isinstance(other, self.__class__):
            all_params = list(sorted(set(self.params.keys()) | set(other.params.keys())))
            self_params = ''.join(((str(k) + str(self.params.get(k))) for k in all_params))
            other_params = ''.join(((str(k) + str(other.params.get(k))) for k in all_params))

            valid = hmac.compare_digest(self.driver_name, other.driver_name)
            valid = hmac.compare_digest(self_params, other_params) and valid
            valid = hmac.compare_digest(self.salt, other.salt) and valid
            valid = hmac.compare_digest(self.hashed_password, other.hashed_password) and valid
            return valid
        else:
            # must be a str
            password = other.encode('utf-8')
            return self.check(password)

    def __str__(self) -> str:
        """Turn a password instance into a JSON object that can be used to fully reconstruct it and its driver"""

        out = {
            'driver_name': self.driver_name,
            'salt': base64.b64encode(self.salt).decode('ascii'),
            'hashed_password': base64.b64encode(self.hashed_password).decode('ascii'),
            'params': self.params
        }
        return json.dumps(out)

    @classmethod
    def parse(cls, encoded: str) -> Any:
        """Parse an encoded password string as generated by str(obj) and turn it into a Password instance"""

        data = json.loads(encoded)
        return cls(
            data['driver_name'],
            base64.b64decode(data['salt']),
            base64.b64decode(data['hashed_password']),
            data['params']
        )

    def check(self, other_password: bytes) -> bool:
        """Test a plaintext password against this one"""

        hashed = self.driver.really_hash_password(self.salt, other_password)
        other = self.__class__(self.driver_name, self.salt, hashed, self.params)
        return self == other


class PasswordHashDriver:
    """\
    A driver implementing a particular password hashing method.

    Most functionality is already implemented - in particular the storage of hash
    type, parameters, salts, etc.  The only required implementation is that of hashing
    a password with a given salt and configured parameters.

    The resulting password data can be stored in the database and used to check
    passwords regardless of the method used to hash them originally, as long as
    the implementation still exists.
    """

    def __init__(self, *args, salt_len: int=16, **kwargs):
        """Initialize the hash driver"""

        self.salt_len = salt_len

    def get_params(self) -> Dict[str, Union[str, int]]:
        """Get the parameters used to initialize this driver"""

        return {
            'salt_len': self.salt_len
        }

    def gen_salt(self) -> bytes:
        """Generate a random salt for use with many hashing algorithms"""
        return os.urandom(self.salt_len)

    def really_hash_password(self, salt: bytes, password: bytes) -> bytes:
        """Hash a password with the given salt and configured params"""
        raise NotImplementedError()

    def hash_password(self, password: bytes, salt: Optional[bytes]=None) -> str:
        """Hash a plaintext password with an optional salt; if no salt is given, one will be generated"""

        salt = salt or self.gen_salt()
        hashed = self.really_hash_password(salt, password)
        pw = Password(
            self.__class__.__name__,
            salt,
            hashed,
            self.get_params()
        )
        return str(pw)

    def check_password(self, stored_password: str, to_check: bytes) -> bool:
        """Check an entered password against a stored password"""

        return Password.parse(stored_password).check(to_check)


class SCryptHashDriver(PasswordHashDriver):
    def __init__(self, *args, n: int=16384, r: int=8, p: int=1, maxmem: int=0, dklen: int=64, **kwargs):
        """\
        Instantiate a hash driver using SCrypt

        * N – iterations count (affects memory and CPU usage), e.g. 16384 (2 ** 14) or 2048 (2 ** 11)
        * R - block size (affects memory and CPU usage), e.g. 8
        * P – parallelism factor (threads to run in parallel - affects the memory, CPU usage), usually 1
        * derived-key-length(dklen) - how many bytes to generate as output, e.g. 32 bytes (256 bits)
        """

        super().__init__(*args, **kwargs)
        self.n = n
        self.r = r
        self.p = p
        self.maxmem = maxmem
        self.dklen = dklen

    def get_params(self):
        params = super().get_params()
        params.update({
            'n': self.n,
            'r': self.r,
            'p': self.p,
            'maxmem': self.maxmem,
            'dklen': self.dklen,
        })
        return params

    def really_hash_password(self, salt: bytes, password: bytes) -> bytes:
        return hashlib.scrypt(
            password, 
            salt=salt,
            n=self.n,
            r=self.r,
            p=self.p,
            maxmem=self.maxmem,
            dklen=self.dklen
        )
