[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]
name = "bc_fsf_mailing_list"
dependencies = [
    "tabulate"
]
requires-python = ">= 3.8"
description = "Add a mailing list to a site"
readme = "README.md"

[tool.setuptools.packages.find]
where = ["src"]