"""\
Base plugin code and application factory
"""

from typing import Callable, Optional, Dict, Any, Iterable, Tuple, Union

import re
import os
import functools
import tempfile
import logging

from flask import Flask, current_app, Blueprint, render_template
from flask.cli import AppGroup
from werkzeug.exceptions import HTTPException
from dotenv import load_dotenv

from . import jinja


logger = logging.getLogger(__name__)


DECORATORS = {}
"""All defined decorators"""

def decorator(name: str, *dec_args, require=False, **dec_kwargs) -> Callable:
    """\
    Apply a decorator to a function call.

    Plugins may define decorators that are optionally available - that is, they
    only exist if the plugin has been installed to the application.

    Using this function to apply the decorator only calls the requested
    decorator if it exists; otherwise the function is called as is.

    Decorators get the args/kwargs provided when decorating as well as the
    args/kwargs the function is called with, and the callback to call.  The
    decorator must determine whether to call the callback or not, and may return
    some other value.

    If require=True, an exception is raised if the requested decorator is not
    available; this is useful for access control decorators where exposing a
    view would be less than ideal.  The exception is not an http response; it is
    meant to crash the application & be fixed
    """
    def decorator_impl(callback: Callable) -> Callable:
        @functools.wraps(callback)
        def decorator_wrap(*call_args, **call_kwargs):
            if name in DECORATORS:
                return DECORATORS[name](callback, dec_args=dec_args, dec_kwargs=dec_kwargs, call_args=call_args, call_kwargs=call_kwargs)
            elif require:
                raise ValueError(f"The required decorator {name} is not available")
            return callback(*call_args, **call_kwargs)
        return decorator_wrap
    return decorator_impl


def require(name: str, *dec_args, **dec_kwargs) -> Callable:
    """\
    Same as calling decorator() with require=True
    """
    return decorator(name, *dec_args, require=True, **dec_kwargs)


class Plugin(jinja.PerPlugin):
    """\
    Custom plugin class providing convenience methods for providing Flask things
    (commands, blueprints, config, etc) and ensuring that plugin code is not run
    unless the plugin is actually installed to the app.
    """

    NAME = None
    """Plugin name - defaults to the snake_case class name, with trailing "Plugin" removed.  Do not use directly, instead use `.name`"""

    def __init__(self, app: Optional[Flask]=None, url_prefix: Optional[str]=None):
        """\
        Initialize the plugin, optionally with the given Flask app.  If a URL
        prefix is given, it is used in the case that a blueprint does not
        provide its own url prefix.
        """

        self.url_prefix = url_prefix
        if app is not None:
            self.init_app(app)

    @property
    def name(self) -> str:
        """\
        Return the plugin's name - either from the NAME attribute or the
        autogenerated name based on the class name.
        """

        return self.NAME or re.sub(r'([a-z])([A-Z])', r'\1_\2', re.sub(r'Plugin$', '', self.__class__.__name__)).lower()

    def get_tempdir(self, plugin: Optional[str]=None) -> str:
        """\
        Return a temporary directory specific to the named plugin within either
        the default temporary directory provided by the tempfile module, or the
        configured temp dir.  If no plugin name is given, the current plugin
        name is used.
        """

        td = os.path.join(current_app.config['TEMP_DIR'], plugin or self.name)
        if not os.path.exists(td):
            os.makedirs(td, exist_ok=True)
        return td

    @property
    def tempdir(self) -> str:
        """\
        Same as `get_tempdir()`, but always for this plugin
        """

        return self.get_tempdir()

    def get_config(self) -> Dict[str, Dict[str, Any]]:
        """\
        Provides this plugin's configuration keys to be fetched from the
        environment.  The return value must be a dict mapping config keys to
        dicts containing any of the following: (all are optional)

        * source: If defined, use this as the key to retrieve from the environment, rather than the outer key
        * parser: Callable to parse the value returned from the environment, if it is not None
        * default: Default value of this config key
        * required: If true, this config key is required and the application will not start without it
        * description: A helpful brief description of the config key
        """

        return {}

    def get_flask_plugins(self) -> Iterable[object]:
        """\
        Provide other Flask plugins to be initialized with the main Flask app
        """
        return []

    def get_blueprints(self) -> Iterable[Tuple[Optional[str], Blueprint]]:
        """\
        Provide blueprints to mount to the Flask app, with an optional URL
        prefix.  If no prefix is given, the global url prefix for this plugin
        is used (if present)
        """

        return []

    def get_commands(self) -> Iterable[AppGroup]:
        """\
        Provide app groups to be registered to the app as commands.
        """

        return []

    def get_decorators(self) -> Dict[str, Callable]:
        """\
        Decorators are explained above, this is the mapping of decorator name
        to callback function provided by the plugin.
        """

        return {}

    def init_app(self, app: Flask):
        """\
        Perform initialization of this plugin, and apply to the app.  If a
        subclass defines init_app, it must call the superclass method.
        """

        super().init_app(app)
        for fplugin in self.get_flask_plugins():
            fplugin.init_app(app)

        for bp_prefix, bp in self.get_blueprints():
            prefix = re.sub(r'/{2,}', '/', '/' + ((self.url_prefix or '') + '/' + (bp_prefix or '')).strip('/'))
            app.register_blueprint(bp, url_prefix=prefix)

        for group in self.get_commands():
            app.cli.add_command(group)

        for dname, dfn in self.get_decorators().items():
            DECORATORS[f'{self.name}.{dname}'] = dfn


class ConfigLoader:
    """\
    Load configuration from the environment, and define default Flask configuration
    """

    def __init__(self):
        """\
        Initialize the config loader with the default Flask config
        """

        self.config_opts = {}
        self.add_opts({
            'SITE_NAME': {
                'parser': str,
                'required': True,
                'description': "Name of the site used for page titles and in other places",
            },
            'DEBUG': {
                'source': ['FLASK_DEBUG', 'DEBUG'],
                'parser': bool,
                'default': False,
                'description': "Whether debug mode is enabled.",
            },
            'TESTING': {
                'source': ['FLASK_TESTING', 'TESTING'],
                'parser': bool,
                'default': False,
                'description': "Enable testing mode.",
            },
            'PROPAGATE_EXCEPTIONS': {
                'parser': bool,
                'description': "Exceptions are re-raised rather than being handled by the app’s error handlers.",
            },
            'TRAP_HTTP_EXCEPTIONS': {
                'parser': bool,
                'default': False,
                'description': "If there is no handler for an HTTPException-type exception, re-raise it to be handled by the interactive debugger instead of returning it as a simple error response.",
            },
            'TRAP_BAD_REQUEST_ERRORS': {
                'parser': bool,
                'description': "Trying to access a key that doesn’t exist from request dicts like args and form will return a 400 Bad Request error page. Enable this to treat the error as an unhandled exception instead so that you get the interactive debugger. This is a more specific version of TRAP_HTTP_EXCEPTIONS. If unset, it is enabled in debug mode.",
            },
            'SECRET_KEY': {
                'parser': str,
                'required': True,
                'description': "A secret key that will be used for securely signing the session cookie and can be used for any other security related needs by extensions or your application.",
            },
            'SESSION_COOKIE_NAME': {
                'parser': str,
                'default': 'session',
                'description': "The name of the session cookie.",
            },
            'SESSION_COOKIE_DOMAIN': {
                'parser': str,
                'description': "The value of the Domain parameter on the session cookie.",
            },
            'SESSION_COOKIE_PATH': {
                'parser': str,
                'description': "The path that the session cookie will be valid for.",
            },
            'SESSION_COOKIE_HTTPONLY': {
                'parser': bool,
                'default': True,
                'description': "Browsers will not allow JavaScript access to cookies marked as “HTTP only” for security.",
            },
            'SESSION_COOKIE_SECURE': {
                'parser': bool,
                'default': False,
                'description': "Browsers will only send cookies with requests over HTTPS if the cookie is marked “secure”.",
            },
            'SESSION_COOKIE_SAMESITE': {
                'parser': str,
                'description': "Restrict how cookies are sent with requests from external sites. Can be set to 'Lax' (recommended) or 'Strict'. See Set-Cookie options.",
            },
            'PERMANENT_SESSION_LIFETIME': {
                'parser': int,
                'default': 2678400,
                'description': "If session.permanent is true, the cookie’s expiration will be set this number of seconds in the future.",
            },
            'SESSION_REFRESH_EACH_REQUEST': {
                'parser': bool,
                'default': True,
                'description': "Control whether the cookie is sent with every response when session.permanent is true.",
            },
            'USE_X_SENDFILE': {
                'parser': bool,
                'default': False,
                'description': "When serving files, set the X-Sendfile header instead of serving the data with Flask.",
            },
            'SEND_FILE_MAX_AGE_DEFAULT': {
                'parser': int,
                'description': "When serving files, set the cache control max age to this number of seconds.",
            },
            'SERVER_NAME': {
                'parser': str,
                'description': "Inform the application what host and port it is bound to.",
            },
            'APPLICATION_ROOT': {
                'parser': str,
                'default': '/',
                'description': "Inform the application what path it is mounted under by the application / web server.",
            },
            'PREFERRED_URL_SCHEME': {
                'parser': str,
                'default': 'http',
                'description': "Use this scheme for generating external URLs when not in a request context.",
            },
            'MAX_CONTENT_LENGTH': {
                'parser': int,
                'description': "Don’t read more than this many bytes from the incoming request data.",
            },
            'TEMPLATES_AUTO_RELOAD': {
                'parser': bool,
                'description': "Reload templates when they are changed.",
            },
            'EXPLAIN_TEMPLATE_LOADING': {
                'parser': bool,
                'default': False,
                'description': "Log debugging information tracing how a template file was loaded.",
            },
            'MAX_COOKIE_SIZE': {
                'parser': int,
                'default': 4093,
                'description': "Warn if cookie headers are larger than this many bytes.",
            },
            'TEMP_DIR': {
                'default': tempfile.gettempdir(),
                'description': "Temporary directory to store generated files or other ephemeral data",
            },
        })

    def add_opts(self, opts: dict):
        """\
        Add additional config options - see the plugin class for details on format
        """

        defaults = {
            'source': None,
            'parser': str,
            'default': None,
            'required': False,
            'description': '',
        }
        for k, v in opts.items():
            if k not in self.config_opts:
                self.config_opts[k] = dict(defaults, **v)

    def _load_one(self, key: str) -> Any:
        """\
        Load a single config value from the environment, parse it, and validate
        whether its presence is required.
        """

        c = self.config_opts.get(key)
        if c:
            value = c['default']
            sources = ([c['source']] if isinstance(c['source'], str) else c['source']) if c['source'] else [key]
            for s in sources:
                v = os.environ.get(s)
                if v is not None:
                    value = v
                    break
            if value is not None:
                try:
                    value = c['parser'](value)
                except Exception as e:
                    raise RuntimeError(f"Failed to parse value {repr(value)} for config key {key}: {e.__class__.__name__}: {e}")
            if c['required'] and value is None:
                raise RuntimeError(f"Config key {key} is required, but not defined")
            return value
        else:
            return os.environ.get(key)

    def __call__(self) -> Dict[str, Any]:
        """\
        Load a .env file into the environment, then load the configuration
        into a dict for later application to the app config itself.
        """

        load_dotenv()
        errors = []
        config = {}
        for k in self.config_opts.keys():
            try:
                v = self._load_one(k)
            except RuntimeError as e:
                errors.append(str(e))
            else:
                config[k] = v
        if errors:
            raise RuntimeError("Config loading failed:\n" + "\n".join(errors))
        return config

    def list(self, config=None):
        for k, v in self.config_opts.items():
            item = dict(v)
            del item['parser']
            item['key'] = k
            item['value'] = (config or {}).get(k)
            yield item


class AppFactory:
    """\
    Generates a Flask application, applying plugins and loading configuration.
    """

    def __init__(self, base_file: str):
        """\
        Create a new app factory with the given file as its base.  This sets up
        a base path at the actual application root instead of in this file's
        folder.
        """

        self.base_path = os.path.dirname(base_file)
        self.plugins = []
        self.error_handlers = {'*': 'base/error.html.j2'}

    def register_plugin(self, plugin: Plugin):
        """\
        Register an instance of a custom plugin class to this factory
        """

        self.plugins.append(plugin)

    def register_error_handler(self, errspec: Union[str, Exception], handler_or_template: Union[str, Callable]):
        """\
        Register an error handler or template for a given code or exception.

        `errspec` must be one of the following:
        * A specific HTTP error code, to handle only that error
        * A string like "4xx" or "5xx" to handle 400-499 or 500-599 respectively
        * A specific range, like "401-403"
        * A comma separated list, like "401,403"
        * An asterisk, "*", to handle all otherwise unhandled HTTPException subclasses
        * A special case, "exc" - in which case the value is 2-tuples of an exception class & either a template name or function

        `handler_or_template` may be an error handler function, or template name to render.

        By default, "*" is sent through "base/error.html.j2"
        """
        if isinstance(errspec, Exception):
            self.error_handlers.setdefault('exc', [])
            self.error_handlers['exc'] = [(e, h) for e, h in self.error_handlers['exc'] if e != errspec]
            self.error_handlers['exc'].append((errspec, handler_or_template))
        else:
            self.error_handlers[errspec] = handler_or_template

    @staticmethod
    def _template_error_handler(template: str, e: Exception) -> Tuple[str, int]:
        """\
        Error handler function to render an error template for a given exception.
        """

        logger.error('%s', e)
        return (
            render_template(
                template,
                err=e,
                code=e.code,
                name=e.name,
                description=e.description
            ),
            e.code
        )

    @classmethod
    def _make_template_error_handler(cls, template: str) -> Callable[[Exception], Callable[[str, Exception], Tuple[str, int]]]:
        """\
        Given a template, generate the error handler to render the template.
        """

        return lambda e: cls._template_error_handler(template, e)

    def _register_error_handlers(self, app: Flask):
        """\
        Register error handlers previously defined
        """

        valid_err = (400,401,403,404,405,406,408,409,410,411,412,413,414,415,417,418,421,422,423,424,428,429,431,451,500,501,502,503,504,505)
        def parse_errspec(es):
            if isinstance(es, int):
                yield es
            else:
                es = str(es)
                if es == '*':
                    yield HTTPException
                elif 'x' in es:
                    start = int(es[0] + '00')
                    yield from range(start, start + 100)
                elif '-' in es:
                    start, end = map(int, es.split('-'))
                    yield from range(start, end + 1)
                elif ',' in es:
                    yield from map(int, es.split(','))

        for errspec, errhandler in self.error_handlers.items():
            if errspec == 'exc':
                for ecls, ehdr in errhandler:
                    handler = ehdr if callable(ehdr) else self._make_template_error_handler(ehdr)
                    app.register_error_handler(ecls, handler)
            else:
                handler = errhandler if callable(errhandler) else self._make_template_error_handler(errhandler)
                for code in parse_errspec(errspec):
                    if isinstance(code, int) and code not in valid_err:
                        continue
                    app.register_error_handler(code, handler)

    def __call__(self) -> Flask:
        """\
        Create the Flask app, loading the config and initializing plugins.
        """

        app = Flask(
            __name__,
            root_path=self.base_path,
            template_folder=os.path.join(self.base_path, 'templates'),
            static_folder=os.path.join(self.base_path, 'static'),
        )

        app.config_loader = ConfigLoader()

        app.base_plugin_module = __name__
        app.plugins = {}
        for p in self.plugins:
            app.plugins[p.name] = p
            app.config_loader.add_opts(p.get_config())

        app.config.update(app.config_loader())

        # Do not init plugins until after config is applied
        for p in self.plugins:
            p.init_app(app)
        # and configure jinja after init_app
        jinja.apply(app)

        # hax
        app.jinja_env.auto_reload = bool(app.config.get('TEMPLATES_AUTO_RELOAD'))

        # more hax - commands not part of a base plugin
        from .commands import cli_config
        app.cli.add_command(cli_config)

        self._register_error_handlers(app)

        return app
